/* eslint-disable @typescript-eslint/no-explicit-any */
import Decimal from "decimal.js";
import { ApiError } from "@/lib/api-errors";
import { prisma } from "@/lib/prisma";
import type { CreditPaymentInput } from "@/schemas/catalog";
import type { z } from "zod";
import { creditAdjustmentSchema } from "@/schemas/catalog";
import { outstandingFor } from "@/services/customer.service";

export async function listCreditEntries(storeId: string, customerId: string, filters: { from?: string; to?: string } = {}) { const customer = await prisma.customer.findFirst({ where: { id: customerId, storeId } }); if (!customer) throw new ApiError("NOT_FOUND", "Customer not found", 404); const createdAt: any = {}; if (filters.from) createdAt.gte = new Date(filters.from); if (filters.to) createdAt.lt = new Date(filters.to); const entries = await prisma.creditLedgerEntry.findMany({ where: { storeId, customerId, ...(Object.keys(createdAt).length ? { createdAt } : {}) }, orderBy: { createdAt: "desc" }, include: { sale: { select: { saleNumber: true } } } }); return { outstanding: await outstandingFor(storeId, customerId), entries: entries.map((entry) => ({ ...entry, amountDelta: entry.amountDelta.toString(), createdAt: entry.createdAt.toISOString() })) }; }
export async function createCreditPayment(storeId: string, userId: string, customerId: string, input: CreditPaymentInput) { return prisma.$transaction(async (tx) => { const customer = await tx.customer.findFirst({ where: { id: customerId, storeId }, include: { creditEntries: { select: { amountDelta: true } } } }); if (!customer) throw new ApiError("NOT_FOUND", "Customer not found", 404); const outstanding = customer.openingCredit.plus(customer.creditEntries.reduce((sum: Decimal, entry: any) => sum.plus(entry.amountDelta), new Decimal(0))); if (new Decimal(input.amount).gt(outstanding)) throw new ApiError("INVALID_PAYMENT", "Payment cannot exceed outstanding credit", 400); const entry = await tx.creditLedgerEntry.create({ data: { storeId, customerId, type: "PAYMENT", amountDelta: new Decimal(input.amount).negated().toFixed(2), paymentMethod: input.paymentMethod, reference: input.reference || null, notes: input.notes || null, createdById: userId } }); return { ...entry, amountDelta: entry.amountDelta.toString(), createdAt: entry.createdAt.toISOString(), outstanding: outstanding.minus(input.amount).toFixed(2) }; }); }
export async function createCreditAdjustment(storeId: string, userId: string, customerId: string, input: z.infer<typeof creditAdjustmentSchema>) { const customer = await prisma.customer.findFirst({ where: { id: customerId, storeId } }); if (!customer) throw new ApiError("NOT_FOUND", "Customer not found", 404); const entry = await prisma.creditLedgerEntry.create({ data: { storeId, customerId, type: input.direction === "DEBIT" ? "ADJUSTMENT_DEBIT" : "ADJUSTMENT_CREDIT", amountDelta: input.direction === "DEBIT" ? input.amount : new Decimal(input.amount).negated().toFixed(2), reference: input.reference || null, notes: input.notes || null, createdById: userId } }); return { ...entry, amountDelta: entry.amountDelta.toString(), createdAt: entry.createdAt.toISOString() }; }
