/* eslint-disable @typescript-eslint/no-explicit-any */
import Decimal from "decimal.js";
import { ApiError } from "@/lib/api-errors";
import { prisma } from "@/lib/prisma";
import type { z } from "zod";
import { inventoryAdjustmentSchema } from "@/schemas/catalog";

function serialize(row: any) { const quantity = row.inventory?.quantity?.toString() ?? "0"; const reorderLevel = row.reorderLevel.toString(); const quantityDecimal = new Decimal(quantity); const reorderDecimal = new Decimal(reorderLevel); return { id: row.id, productId: row.id, name: row.name, sku: row.sku, category: row.category, quantity, reorderLevel, defaultBuyPrice: row.defaultBuyPrice?.toString() ?? null, mrp: row.mrp.toString(), status: quantityDecimal.eq(0) ? "OUT" : quantityDecimal.lte(reorderDecimal) ? "LOW" : "IN_STOCK" }; }
export async function listInventory(storeId: string, filters: { search?: string; categoryId?: string; status: "LOW" | "OUT" | "ALL"; page: number; pageSize: number }) { const products = await prisma.product.findMany({ where: { storeId, ...(filters.search ? { OR: [{ name: { contains: filters.search, mode: "insensitive" as const } }, { sku: { contains: filters.search, mode: "insensitive" as const } }] } : {}), ...(filters.categoryId ? { categoryId: filters.categoryId } : {}) }, include: { inventory: true, category: { select: { id: true, name: true } } }, orderBy: { name: "asc" } }); const filtered = products.map(serialize).filter((row) => filters.status === "ALL" || row.status === filters.status); return { items: filtered.slice((filters.page - 1) * filters.pageSize, filters.page * filters.pageSize), total: filtered.length, page: filters.page, pageSize: filters.pageSize }; }
export async function adjustInventory(storeId: string, userId: string, input: z.infer<typeof inventoryAdjustmentSchema>) { return prisma.$transaction(async (tx) => { const product = await tx.product.findFirst({ where: { id: input.productId, storeId }, include: { inventory: true } }); if (!product) throw new ApiError("FORBIDDEN", "Product does not belong to this store", 403); const delta = new Decimal(input.quantity).times(input.direction === "IN" ? 1 : -1); if (input.direction === "OUT" && (!product.inventory || new Decimal(product.inventory.quantity.toString()).lt(input.quantity))) throw new ApiError("INSUFFICIENT_STOCK", "Insufficient stock for adjustment", 409); await tx.inventoryMovement.create({ data: { storeId, productId: input.productId, type: input.direction === "IN" ? "ADJUSTMENT_IN" : "ADJUSTMENT_OUT", quantityDelta: delta.toFixed(3), notes: input.reason, createdById: userId } }); const balance = await tx.inventoryBalance.upsert({ where: { productId: input.productId }, create: { productId: input.productId, quantity: delta.toFixed(3) }, update: { quantity: { increment: delta.toFixed(3) } } }); return { productId: product.id, quantity: balance.quantity.toString() }; }); }
export async function reconcileInventory(storeId: string) { const products = await prisma.product.findMany({ where: { storeId }, include: { inventory: true, stockMoves: { select: { quantityDelta: true } } } }); return products.map((product) => ({ productId: product.id, cachedQuantity: product.inventory?.quantity.toString() ?? "0", movementQuantity: product.stockMoves.reduce((sum, move) => sum.plus(move.quantityDelta), new Decimal(0)).toFixed(3), matches: new Decimal(product.inventory?.quantity.toString() ?? "0").eq(product.stockMoves.reduce((sum, move) => sum.plus(move.quantityDelta), new Decimal(0))) })); }
