import { useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import { AppShell } from "@/components/layout/AppShell";
import { CreditPaymentForm } from "@/components/forms/CreditPaymentForm";
import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { ErrorState } from "@/components/ui/ErrorState";
import { LoadingState } from "@/components/ui/LoadingState";
import { Modal } from "@/components/ui/Modal";
import { Table } from "@/components/ui/Table";
import { useCustomer, useCustomerCredit } from "@/features/customers/use-customers";
import type { CreditPaymentInput } from "@/schemas/catalog";
export default function CustomerDetailPage() { const router = useRouter(); const id = typeof router.query.id === "string" ? router.query.id : undefined; const customer = useCustomer(id); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const credit = useCustomerCredit(id, { from: from || undefined, to: to || undefined }); const [open, setOpen] = useState(false); const [success, setSuccess] = useState(false); const pay = async (input: CreditPaymentInput) => { await credit.makePayment(input); setOpen(false); setSuccess(true); }; return <><Head><title>Customer credit | Kirana Store Manager</title></Head><AppShell title="Customer credit"><div className="space-y-6">{(customer.isPending || credit.isPending) && <LoadingState label="Loading customer credit…" />}{(customer.isError || credit.isError) && <ErrorState message={(customer.error || credit.error)?.message ?? "Unable to load customer"} onRetry={() => { void customer.refetch(); void credit.refetch(); }} />}{customer.data && credit.data && <><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-brand-600">Customer</p><h2 className="mt-1 text-2xl font-bold text-content">{customer.data.name}</h2><p className="mt-1 text-sm text-content-muted">{customer.data.phone || "No phone number"}</p></div><Button onClick={() => setOpen(true)}>Record payment</Button></div>{success && <Alert tone="success">Payment recorded.</Alert>}<Card className="p-4"><div className="grid gap-3 md:grid-cols-2"><label className="text-sm text-content-muted">From<input className="mt-1 h-11 w-full rounded-control border border-border bg-surface px-3 text-sm text-content" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></label><label className="text-sm text-content-muted">To<input className="mt-1 h-11 w-full rounded-control border border-border bg-surface px-3 text-sm text-content" type="date" value={to} onChange={(event) => setTo(event.target.value)} /></label></div></Card><Card className="p-5"><p className="text-sm text-content-muted">Current outstanding</p><p className="mt-2 text-3xl font-bold text-content">₹{credit.data.outstanding}</p></Card><Card className="overflow-hidden"><Table rows={credit.data.entries} getRowKey={(row) => row.id} columns={[{ key: "date", header: "Date", render: (row) => new Date(row.createdAt).toLocaleString() }, { key: "type", header: "Type", render: (row) => row.type }, { key: "amount", header: "Change", render: (row) => `₹${row.amountDelta}` }, { key: "reference", header: "Reference", render: (row) => row.reference || row.sale?.saleNumber || "—" }]} /></Card></>}</div></AppShell><Modal open={open} title="Record credit payment" onClose={() => setOpen(false)}><CreditPaymentForm isSaving={credit.isSaving} serverError={credit.saveError?.message} onSubmit={pay} onCancel={() => setOpen(false)} /></Modal></>; }
