import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import { AppShell } from "@/components/layout/AppShell";
import { CustomerForm } from "@/components/forms/CustomerForm";
import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { EmptyState } from "@/components/ui/EmptyState";
import { ErrorState } from "@/components/ui/ErrorState";
import { Input } from "@/components/ui/Input";
import { LoadingState } from "@/components/ui/LoadingState";
import { Modal } from "@/components/ui/Modal";
import { Table } from "@/components/ui/Table";
import { useCustomers, type Customer } from "@/features/customers/use-customers";
import type { CustomerInput } from "@/schemas/catalog";
export default function CustomersPage() { const [search, setSearch] = useState(""); const [editing, setEditing] = useState<Customer | undefined>(); const [open, setOpen] = useState(false); const [success, setSuccess] = useState(false); const customers = useCustomers({ search, page: 1, pageSize: 100 }); const save = async (input: CustomerInput) => { await customers.saveCustomer({ id: editing?.id, input }); setOpen(false); setEditing(undefined); setSuccess(true); }; return <><Head><title>Customers | Kirana Store Manager</title></Head><AppShell title="Customers"><div className="space-y-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-brand-600">Credit accounts</p><h2 className="mt-1 text-2xl font-bold text-content">Customers</h2><p className="mt-1 text-sm text-content-muted">Manage regular customers and outstanding credit.</p></div><Button onClick={() => { setEditing(undefined); setOpen(true); }}>Add customer</Button></div>{success && <Alert tone="success">Customer saved successfully.</Alert>}<Card className="p-4"><Input placeholder="Search by name or phone" value={search} onChange={(event) => setSearch(event.target.value)} /></Card>{customers.isPending && <LoadingState label="Loading customers…" />}{customers.isError && <ErrorState message={customers.error.message} onRetry={() => void customers.refetch()} />}{customers.data?.items.length === 0 && <EmptyState title="No customers found" description="Add a customer to enable credit sales." />}{customers.data && customers.data.items.length > 0 && <Card className="overflow-hidden"><Table rows={customers.data.items} getRowKey={(row) => row.id} columns={[{ key: "name", header: "Name", render: (row) => <Link className="font-semibold text-brand-700" href={`/customers/${row.id}`}>{row.name}</Link> }, { key: "phone", header: "Phone", render: (row) => row.phone || "—" }, { key: "outstanding", header: "Outstanding", render: (row) => `₹${row.outstanding}` }, { key: "limit", header: "Credit limit", render: (row) => row.creditLimit ? `₹${row.creditLimit}` : "No limit" }, { key: "actions", header: "", render: (row) => <Button size="sm" variant="ghost" onClick={() => { setEditing(row); setOpen(true); }}>Edit</Button> }]} /></Card>}</div></AppShell><Modal open={open} title={editing ? "Edit customer" : "Add customer"} onClose={() => setOpen(false)}><CustomerForm initialValues={editing ? { name: editing.name, phone: editing.phone ?? "", address: editing.address ?? "", creditLimit: editing.creditLimit ?? "", openingCredit: editing.openingCredit, isActive: editing.isActive } : undefined} isSaving={customers.isSaving} serverError={customers.saveError?.message} onSubmit={save} onCancel={() => setOpen(false)} /></Modal></>; }
