/* eslint-disable @typescript-eslint/no-explicit-any */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "@/features/auth/auth-context";
import { apiRequest } from "@/lib/api-client";
import { queryKeys } from "@/lib/query-keys";
import type { CreditPaymentInput, CustomerInput } from "@/schemas/catalog";
export type Customer = { id: string; name: string; phone: string | null; address: string | null; creditLimit: string | null; openingCredit: string; isActive: boolean; outstanding?: string };
export function useCustomers(filters: { search?: string; page: number; pageSize: number }) { const { session } = useAuth(); const client = useQueryClient(); const query = useQuery({ queryKey: queryKeys.customers(filters), queryFn: () => apiRequest<{ items: Customer[]; total: number; page: number; pageSize: number }>(session, `/api/customers?page=${filters.page}&pageSize=${filters.pageSize}&search=${encodeURIComponent(filters.search ?? "")}`), enabled: Boolean(session) }); const mutation = useMutation({ mutationFn: ({ id, input }: { id?: string; input: CustomerInput }) => apiRequest<Customer>(session, id ? `/api/customers/${id}` : "/api/customers", { method: id ? "PATCH" : "POST", body: JSON.stringify(input) }), onSuccess: () => client.invalidateQueries({ queryKey: ["customers"] }) }); return { ...query, saveCustomer: mutation.mutateAsync, isSaving: mutation.isPending, saveError: mutation.error }; }
export function useCustomer(id?: string) { const { session } = useAuth(); return useQuery({ queryKey: queryKeys.customer(id ?? ""), queryFn: () => apiRequest<Customer & { creditEntries: any[] }>(session, `/api/customers/${id}`), enabled: Boolean(session && id) }); }
export function useCustomerCredit(id?: string, filters: { from?: string; to?: string } = {}) { const { session } = useAuth(); const client = useQueryClient(); const query = useQuery({ queryKey: [...queryKeys.customerCredit(id ?? ""), filters], queryFn: () => apiRequest<{ outstanding: string; entries: any[] }>(session, `/api/customers/${id}/credit?from=${filters.from ?? ""}&to=${filters.to ?? ""}`), enabled: Boolean(session && id) }); const mutation = useMutation({ mutationFn: (input: CreditPaymentInput) => apiRequest<any>(session, `/api/customers/${id}/credit`, { method: "POST", body: JSON.stringify(input) }), onSuccess: () => { void client.invalidateQueries({ queryKey: queryKeys.customerCredit(id ?? "") }); void client.invalidateQueries({ queryKey: ["customers"] }); } }); return { ...query, makePayment: mutation.mutateAsync, isSaving: mutation.isPending, saveError: mutation.error }; }
