import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { customerSchema, type CustomerInput } from "@/schemas/catalog";
import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { Checkbox } from "@/components/ui/Checkbox";
import { FormField } from "@/components/ui/FormField";
import { Input } from "@/components/ui/Input";
import { Textarea } from "@/components/ui/Textarea";
export function CustomerForm({ initialValues, isSaving, serverError, onSubmit, onCancel }: { initialValues?: CustomerInput; isSaving: boolean; serverError?: string; onSubmit: (values: CustomerInput) => Promise<void>; onCancel: () => void }) { const { register, reset, handleSubmit, formState: { errors } } = useForm<CustomerInput>({ resolver: zodResolver(customerSchema) as never, defaultValues: initialValues ?? { name: "", phone: "", address: "", creditLimit: "", openingCredit: "0", isActive: true } }); useEffect(() => { reset(initialValues ?? { name: "", phone: "", address: "", creditLimit: "", openingCredit: "0", isActive: true }); }, [initialValues, reset]); return <form className="space-y-5" onSubmit={(event) => void handleSubmit(onSubmit)(event)}><div className="grid gap-4 md:grid-cols-2"><FormField label="Name" htmlFor="customer-name" error={errors.name?.message}><Input id="customer-name" autoFocus {...register("name")} /></FormField><FormField label="Phone" htmlFor="customer-phone" error={errors.phone?.message}><Input id="customer-phone" {...register("phone")} /></FormField><FormField label="Credit limit" htmlFor="customer-limit" error={errors.creditLimit?.message}><Input id="customer-limit" {...register("creditLimit")} /></FormField><FormField label="Opening credit" htmlFor="customer-opening" error={errors.openingCredit?.message}><Input id="customer-opening" {...register("openingCredit")} /></FormField></div><FormField label="Address" htmlFor="customer-address"><Textarea id="customer-address" {...register("address")} /></FormField><label className="flex items-center gap-2 text-sm"><Checkbox {...register("isActive")} /> Active customer</label>{serverError && <Alert tone="danger">{serverError}</Alert>}<div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={isSaving}>{isSaving ? "Saving…" : "Save customer"}</Button></div></form>; }
