import { useEffect } from "react";
import { useFieldArray, useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { purchaseSchema, type PurchaseInput } from "@/schemas/catalog";
import { Alert } from "@/components/ui/Alert";
import { Button } from "@/components/ui/Button";
import { FormField } from "@/components/ui/FormField";
import { Input } from "@/components/ui/Input";
import { Select } from "@/components/ui/Select";

export function PurchaseForm({ products, suppliers, isSaving, serverError, onSubmit, onCancel }: { products: { id: string; name: string; defaultBuyPrice: string | null; mrp: string }[]; suppliers: { id: string; name: string }[]; isSaving: boolean; serverError?: string; onSubmit: (values: PurchaseInput) => Promise<void>; onCancel: () => void }) {
  const { register, control, watch, setValue, handleSubmit, formState: { errors } } = useForm<PurchaseInput>({ resolver: zodResolver(purchaseSchema) as never, defaultValues: { purchaseDate: new Date().toISOString().slice(0, 10), supplierId: null, invoiceNumber: "", notes: "", items: [{ productId: products[0]?.id ?? "", quantity: "1", buyPrice: products[0]?.defaultBuyPrice ?? "0", mrpAtPurchase: products[0]?.mrp ?? "0", discount: "0", taxRate: "0" }] } });
  const { fields, append, remove } = useFieldArray({ control, name: "items" }); const items = watch("items"); useEffect(() => { if (products.length && items[0]?.productId === "") setValue("items.0.productId", products[0].id); }, [products, items, setValue]);
  return <form className="space-y-5" onSubmit={(event) => void handleSubmit(onSubmit)(event)}><div className="grid gap-4 md:grid-cols-3"><FormField label="Supplier" htmlFor="purchase-supplier"><Select id="purchase-supplier" {...register("supplierId")}><option value="">Walk-in supplier</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</Select></FormField><FormField label="Invoice number" htmlFor="purchase-invoice"><Input id="purchase-invoice" {...register("invoiceNumber")} /></FormField><FormField label="Purchase date" htmlFor="purchase-date" error={errors.purchaseDate?.message}><Input id="purchase-date" type="date" {...register("purchaseDate")} /></FormField></div><div className="space-y-3">{fields.map((field, index) => <div key={field.id} className="grid gap-3 rounded-control border border-border p-3 md:grid-cols-[2fr_1fr_1fr_1fr_1fr_auto]"><FormField label="Product" htmlFor={`purchase-product-${index}`} error={errors.items?.[index]?.productId?.message}><Select id={`purchase-product-${index}`} {...register(`items.${index}.productId` as const)}>{products.map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</Select></FormField><FormField label="Quantity" htmlFor={`purchase-quantity-${index}`} error={errors.items?.[index]?.quantity?.message}><Input id={`purchase-quantity-${index}`} {...register(`items.${index}.quantity` as const)} /></FormField><FormField label="Buy price" htmlFor={`purchase-buy-${index}`}><Input id={`purchase-buy-${index}`} {...register(`items.${index}.buyPrice` as const)} /></FormField><FormField label="MRP" htmlFor={`purchase-mrp-${index}`}><Input id={`purchase-mrp-${index}`} {...register(`items.${index}.mrpAtPurchase` as const)} /></FormField><FormField label="Tax %" htmlFor={`purchase-tax-${index}`}><Input id={`purchase-tax-${index}`} {...register(`items.${index}.taxRate` as const)} /></FormField><Button type="button" variant="ghost" onClick={() => remove(index)} disabled={fields.length === 1}>Remove</Button></div>)}</div><Button type="button" variant="secondary" onClick={() => append({ productId: products[0]?.id ?? "", quantity: "1", buyPrice: products[0]?.defaultBuyPrice ?? "0", mrpAtPurchase: products[0]?.mrp ?? "0", discount: "0", taxRate: "0" })}>Add product</Button><FormField label="Notes" htmlFor="purchase-notes"><Input id="purchase-notes" {...register("notes")} /></FormField>{serverError && <Alert tone="danger">{serverError}</Alert>}<div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={isSaving}>{isSaving ? "Saving…" : "Complete purchase"}</Button></div></form>;
}
